services:
  jenkins:
    container_name: jenkins_esteban
    #add node image
    build:
      dockerfile: ../common/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home: